let univGenre = [
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2007,
    "Période": "",
    "GEO_PICT": "VU",
    "Pays et territoires insulaires du Pacifique": "Vanuatu",
    "INDICATOR": "GAR_5T8_M",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": 2.78,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2018,
    "Période": "",
    "GEO_PICT": "PG",
    "Pays et territoires insulaires du Pacifique": "Papouasie-Nouvelle-Guinée",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 3.96,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2018,
    "Période": "",
    "GEO_PICT": "PG",
    "Pays et territoires insulaires du Pacifique": "Papouasie-Nouvelle-Guinée",
    "INDICATOR": "GAR_5T8_M",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": 3.4,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "KI",
    "Pays et territoires insulaires du Pacifique": "Kiribati",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 5.89,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
    {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "KI",
    "Pays et territoires insulaires du Pacifique": "Kiribati",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": null,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "TO",
    "Pays et territoires insulaires du Pacifique": "Tonga",
    "INDICATOR": "GAR_5T8_M",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": 9.86,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2007,
    "Période": "",
    "GEO_PICT": "VU",
    "Pays et territoires insulaires du Pacifique": "Vanuatu",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 1.31,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "WS",
    "Pays et territoires insulaires du Pacifique": "Samoa",
    "INDICATOR": "GAR_5T8_M",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": 16.53,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2020,
    "Période": "",
    "GEO_PICT": "TV",
    "Pays et territoires insulaires du Pacifique": "Tuvalu",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 21.71,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "WS",
    "Pays et territoires insulaires du Pacifique": "Samoa",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 23.84,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "TO",
    "Pays et territoires insulaires du Pacifique": "Tonga",
    "INDICATOR": "GAR_5T8_F",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), femmes (%)",
    "OBS_VALUE": 16.76,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2020,
    "Période": "",
    "GEO_PICT": "TV",
    "Pays et territoires insulaires du Pacifique": "Tuvalu",
    "INDICATOR": "GAR_5T8_M",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquête auprès des ménages), hommes (%)",
    "OBS_VALUE": 11.42,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  }
]