let univ = [
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "KI",
    "Pays et territoires insulaires du Pacifique": "Kiribati",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 4.27,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2018,
    "Période": "",
    "GEO_PICT": "PG",
    "Pays et territoires insulaires du Pacifique": "Papouasie-Nouvelle-Guinée",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 3.68,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "TO",
    "Pays et territoires insulaires du Pacifique": "Tonga",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 13.37,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2020,
    "Période": "",
    "GEO_PICT": "TV",
    "Pays et territoires insulaires du Pacifique": "Tuvalu",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 16.15,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2007,
    "Période": "",
    "GEO_PICT": "VU",
    "Pays et territoires insulaires du Pacifique": "Vanuatu",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 1.98,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  },
  {
    "STRUCTURE": "DATAFLOW",
    "STRUCTURE_ID": "SPC:DF_UIS(1.0)",
    "STRUCTURE_NAME": "Indicateurs thématiques (objectif 4 des ODD) sur l'éducation",
    "ACTION": "I",
    "FREQ": "A",
    "Fréquence": "Annuel",
    "TIME_PERIOD": 2019,
    "Période": "",
    "GEO_PICT": "WS",
    "Pays et territoires insulaires du Pacifique": "Samoa",
    "INDICATOR": "GAR_5T8",
    "Indicateur": "Taux brut de fréquentation de l'enseignement supérieur (données d'enquêtes auprès des ménages), deux sexes (%)",
    "OBS_VALUE": 20.01,
    "Valeur observée": "",
    "UNIT_MEASURE": "",
    "Unité de mesure": "",
    "UNIT_MULT": "",
    "Multiplicateur d'unités": "",
    "OBS_STATUS": "",
    "Statut de l'observation": "",
    "DATA_SOURCE": "",
    "Source de données": "",
    "OBS_COMMENT": "",
    "Commentaire": ""
  }
]